=== KikeVera/SEW_XML/Ejercicio-2/Tarea-1/Release/arbol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://tempuri.org/arbol" elementFormDefault="qualified" targetNamespace="http://tempuri.org/arbol" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="arbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="persona" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="persona">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datos" />
				<xs:element minOccurs="0" maxOccurs="2" ref="persona" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="apellidos" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="datos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datosNacimiento" />
				<xs:element minOccurs="0" maxOccurs="1" ref="datosFallecimiento" />
				<xs:element ref="fotografias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="videos" />
				<xs:element ref="comentarios" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="datosNacimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fechaNacimiento" />
				<xs:element ref="lugarNacimiento" />
				<xs:element ref="coordenadasNacimiento" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaNacimiento" type="xs:date" />
	<xs:element name="lugarNacimiento" type="xs:string" />
	<xs:element name="coordenadasNacimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:float" />
	<xs:element name="latitud" type="xs:float" />
	<xs:element name="altitud" type="xs:float" />
	<xs:element name="datosFallecimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fechaFallecimiento" />
				<xs:element ref="lugarFallecimiento" />
				<xs:element ref="coordenadasFallecimiento" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaFallecimiento" type="xs:date" />
	<xs:element name="lugarFallecimiento" type="xs:string" />
	<xs:element name="coordenadasFallecimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="comentarios">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="comentario" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comentario" type="xs:string" />
</xs:schema>

=== KikeVera/SEW_XML/Ejercicio-2/Tarea-2/Release/arbol.xml
<?xml version="1.0" encoding="UTF-8"?>

<arbol xmlns="http://tempuri.org/arbol" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tempuri.org/arbol arbol.xsd">


<persona nombre="Enrique" apellidos="Vera Cueto">  <!--Hijo-->
<datos>
<datosNacimiento>
<fechaNacimiento>1996-11-19</fechaNacimiento>
<lugarNacimiento>Oviedo</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-5.873420193275075</longitud>
<latitud>43.341920421217154</latitud>
<altitud>232</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<fotografias>
<foto>fotoHijo1.jpg</foto>
<foto>fotoHijo2.jpg</foto>
<foto>fotoHijo3.jpg</foto>

</fotografias>


<videos>
<video>videoHijo1.mp4</video>
<video>videoHijo2.mp4</video>
<video>videoHijo3.mp4</video>
</videos>


<comentarios>
<comentario>Primer comentario Enrique</comentario>
<comentario>Segundo comentario Enrique</comentario>
<comentario>Tercer comentario Enrique</comentario>

</comentarios>


</datos>

<persona nombre="Pablo" apellidos="Vera de la Puente"> <!--Padre-->
<datos>
<datosNacimiento>
<fechaNacimiento>1965-03-25</fechaNacimiento>
<lugarNacimiento>Oviedo</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-5.874420193275075</longitud>
<latitud>43.341920421217154</latitud>
<altitud>232</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<fotografias>
<foto>fotoPadre1.jpg</foto>


</fotografias>

<videos>
<video>videoPadre1.mp4</video>
</videos>


<comentarios>
<comentario>Primer comentario Pablo</comentario>
<comentario>Segundo comentario Pablo</comentario>

</comentarios>


</datos>
<persona nombre="Enrique" apellidos="Vera González"> <!--Abuelo paterno-->
<datos>

<datosNacimiento>
<fechaNacimiento>1918-07-15</fechaNacimiento>
<lugarNacimiento>Burgos</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-3.716286</longitud>
<latitud>42.284055</latitud>
<altitud>872</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1996-04-10</fechaFallecimiento>
<lugarFallecimiento>Latores</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-5.879365</longitud>
<latitud>43.311533</latitud>
<altitud>165</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoPadreAbuelo1.jpg</foto>


</fotografias>





<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>
<persona nombre="Enrique" apellidos="Vera Sancha"> <!--Bisabuelo paterno paterno-->
<datos>

<datosNacimiento>
<fechaNacimiento>1890-02-22</fechaNacimiento>
<lugarNacimiento>Villamayor de los Montes</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-3.765112</longitud>
<latitud>42.097845</latitud>
<altitud>907</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1971-07-10</fechaFallecimiento>
<lugarFallecimiento>Lerma</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-3.787987</longitud>
<latitud>41.992695</latitud>
<altitud>912</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoPadreAbueloBisabuelo1.jpg</foto>


</fotografias>





<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>
</persona>
<persona nombre="Clotilde" apellidos="González Vera"> <!--Bisabuela paterna paterna-->
<datos>

<datosNacimiento>
<fechaNacimiento>1892-08-16</fechaNacimiento>
<lugarNacimiento>Santoña</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-3.485646</longitud>
<latitud>43.364921</latitud>
<altitud>33</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1971-09-09</fechaFallecimiento>
<lugarFallecimiento>Lerma</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-3.787987</longitud>
<latitud>41.992695</latitud>
<altitud>912</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoPadreAbueloBisabuela1.jpg</foto>


</fotografias>





<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>
</persona>
</persona>
<persona nombre="Carmen" apellidos="de la Puente de la Puente"> <!--Abuela paterna-->
<datos>

<datosNacimiento>
<fechaNacimiento>1926-01-20</fechaNacimiento>
<lugarNacimiento>Burgos</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-3.716292</longitud>
<latitud>42.284062</latitud>
<altitud>865</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>2018-01-28</fechaFallecimiento>
<lugarFallecimiento>Latores</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-5.879365</longitud>
<latitud>43.311533</latitud>
<altitud>165</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoPadreAbuela1.jpg</foto>
<foto>fotoPadreAbuela2.jpg</foto>

</fotografias>


<videos>
<video>videoPadreAbuela1.mp4</video>
</videos>


<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>
<persona nombre="Luis" apellidos="de la Puente López"> <!--Bisabuelo paterno materno-->
<datos>

<datosNacimiento>
<fechaNacimiento>1896-03-18</fechaNacimiento>
<lugarNacimiento>Burgos</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-3.716298</longitud>
<latitud>42.284043</latitud>
<altitud>872</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1983-04-18</fechaFallecimiento>
<lugarFallecimiento>Madrid</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-3.732979</longitud>
<latitud>40.348525</latitud>
<altitud>620</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoPadreAbuelaBisabuelo1.jpg</foto>
<foto>fotoPadreAbuelaBisabuelo2.jpg</foto>

</fotografias>


<videos>
<video>videoPadreAbuelaBisabuelo1.mp4</video>
</videos>


<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>


</persona>
<persona nombre="Carmen" apellidos="de la Puente Medina"> <!--Bisabuela paterna materna-->
<datos>

<datosNacimiento>
<fechaNacimiento>1898-10-22</fechaNacimiento>
<lugarNacimiento>Briviesca</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-3.337606</longitud>
<latitud>42.548809</latitud>
<altitud>751</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1983-06-27</fechaFallecimiento>
<lugarFallecimiento>Madrid</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-3.732979</longitud>
<latitud>40.348525</latitud>
<altitud>620</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoPadreAbuelaBisabuela1.jpg</foto>
<foto>fotoPadreAbuelaBisabuela2.jpg</foto>

</fotografias>


<videos>
<video>videoPadreAbuelaBisabuela1.mp4</video>
</videos>


<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>


</persona>
</persona>


</persona>



<persona nombre="María" apellidos="Cueto Sánchez"> <!--Madre-->
<datos>
<datosNacimiento>
<fechaNacimiento>1966-07-22</fechaNacimiento>
<lugarNacimiento>Oviedo</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-5.873520193275075</longitud>
<latitud>43.241920421217154</latitud>
<altitud>232</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<fotografias>
<foto>fotoMadre1.jpg</foto>


</fotografias>



<comentarios>
<comentario>Primer comentario Enrique</comentario>
<comentario>Segundo comentario Enrique</comentario>

</comentarios>


</datos>
<persona nombre="Jose Luis" apellidos="Cueto Fernández"> <!--Abuelo materno-->
<datos>

<datosNacimiento>
<fechaNacimiento>1924-09-12</fechaNacimiento>
<lugarNacimiento>Coviella</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-5.173368</longitud>
<latitud>43.382490</latitud>
<altitud>89</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1998-08-12</fechaFallecimiento>
<lugarFallecimiento>Oviedo</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-5.870055</longitud>
<latitud>43.354016</latitud>
<altitud>280</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoMadreAbuelo1.jpg</foto>


</fotografias>



<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>
<persona nombre="Manuel" apellidos="Cueto Arias"> <!--Bisabuelo materno paterno-->
<datos>

<datosNacimiento>
<fechaNacimiento>1895-07-07</fechaNacimiento>
<lugarNacimiento>Arriondas</lugarNacimiento>
<coordenadasNacimiento>
<longitud>-5.180138</longitud>
<latitud>43.375815</latitud>
<altitud>36</altitud>


</coordenadasNacimiento>
</datosNacimiento>

<datosFallecimiento>
<fechaFallecimiento>1964-11-12</fechaFallecimiento>
<lugarFallecimiento>Coviella</lugarFallecimiento>
<coordenadasFallecimiento>
<longitud>-5.178672</longitud>
<latitud>43.376511</latitud>
<altitud>92</altitud>


</coordenadasFallecimiento>
</datosFallecimiento>

<fotografias>
<foto>fotoMadreAbueloBisabuelo1.jpg</foto>


</fotografias>




<comentarios>
<comentario>Primer comentario xxxx</comentario>
<comentario>Segundo comentario xxx</comentario>

</comentarios>


</datos>


</persona>
<persona nombre="Remedios" apellidos="Fernández Onís"> <!--Bisabuela materna paterna-->
<datos>

<datosNacimiento>
